# Generated by Django 3.2.17 on 2023-08-24 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0003_household_location_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='household',
            field=models.ForeignKey(
                blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.household'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(
                blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='room',
            field=models.ForeignKey(
                blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.room'),
            preserve_default=False,
        ),
    ]
