# Generated by Django 3.2.17 on 2023-08-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0007_alter_stockhistory_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='reorder_level',
            field=models.IntegerField(blank='3', default='3', null=True),
        ),
    ]
