# Generated by Django 3.2.17 on 2023-08-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0009_auto_20230827_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item_notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
