# Generated by Django 3.2.17 on 2023-09-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0014_stock_has_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_issued_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
