# Generated by Django 3.2.17 on 2023-09-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0015_stock_total_issued_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='total_issued_quantity',
        ),
    ]
