# Generated by Django 3.2.17 on 2023-09-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0017_auto_20230904_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='issue_reason',
            new_name='item_usage',
        ),
    ]
