# Generated by Django 3.2.17 on 2023-09-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0019_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.household'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.location'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.room'),
        ),
    ]
