# Generated by Django 3.2.17 on 2023-09-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0020_auto_20230906_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='household',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.household'),
        ),
    ]
