# Generated by Django 3.2.17 on 2023-09-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0026_auto_20230906_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='household',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='room',
        ),
    ]
