# Generated by Django 3.2.17 on 2023-09-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0027_auto_20230906_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
