# Generated by Django 3.2.17 on 2023-09-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0029_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Which room is the item at?', max_length=50, null=True),
        ),
    ]
