# Generated by Django 3.2.17 on 2023-09-07 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0030_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='What category is the item related to? (such Cables/Computer Parts/Tools?)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Where is the item located?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.household'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.location'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.room'),
        ),
    ]
