# Generated by Django 3.2.17 on 2023-09-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0036_alter_stock_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='item_usage',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
